name: wei_flutter Build Development
on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.6.1
        with:
          flutter-version: '3.0.5'
          
      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/my_production.keystore

      - name: Build
        run: |
          sed -i "s^value1^\'${{ secrets.VALUE1 }}\'^g" $GITHUB_WORKSPACE/lib/config.dart
          sed -i "s^value2^\'${{ secrets.VALUE2 }}\'^g" $GITHUB_WORKSPACE/lib/config.dart
          sed -i "s^value3^\'${{ secrets.VALUE3 }}\'^g" $GITHUB_WORKSPACE/lib/config.dart
          flutter pub get
          flutter analyze
          flutter test
          flutter build appbundle --release --flavor prod

      - name: Sign Android App Bundle
        run: jarsigner -keystore $RUNNER_TEMP/my_production.keystore -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEYSTORE_PASSWORD_ALIAS }} -sigalg SHA256withRSA -digestalg SHA-256 -signedjar build/app/outputs/bundle/prodRelease/app-release-signed.aab build/app/outputs/bundle/prodRelease/*.aab myKey

      - name: Publish Android Artefacts
        uses: actions/upload-artifact@v1
        with:
          name: release-aab-signed
          path: build/app/outputs/bundle/prodRelease/app-release-signed.aab
      
#      - name: Create a Release AAB
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/bundle/prodRelease/*.aab"
#          token: ${{ secrets.TOKEN }}
